# Generated by Django 5.2.9 on 2026-04-08 07:10

import modules.core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statistics',
            field=models.JSONField(blank=True, default=modules.core.models.user.UserStatisticsSchema.to_dict, verbose_name='Статистика пользователя'),
        ),
    ]
